services:
  - type: web
    name: bedtime-story-generator
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # User must set this manually
    healthCheckPath: /
